# Project: secao07exercicio07
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = secao07exercicio07.o
LINKOBJ  = secao07exercicio07.o
LIBS     = -L"A:/programacao/dev-C++/Dev-Cpp/MinGW64/lib" -L"A:/programacao/dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"A:/programacao/dev-C++/Dev-Cpp/MinGW64/include" -I"A:/programacao/dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"A:/programacao/dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"A:/programacao/dev-C++/Dev-Cpp/MinGW64/include" -I"A:/programacao/dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"A:/programacao/dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"A:/programacao/dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = secao07exercicio07.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

secao07exercicio07.o: secao07exercicio07.cpp
	$(CPP) -c secao07exercicio07.cpp -o secao07exercicio07.o $(CXXFLAGS)
